window.games = [
	{
		title: 'Contra',
		boxArt: 'https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/1280x1280/products/24588/22898/Contra__12672.1398107831.jpg?c=2&imbypass=on',
		publisher: 'Konami',
		releaseYear: '1987',
		platform: 'NES',
		imageLink: 'http://classicgamesblog.com/wp-content/uploads/2012/07/Contra-NES-Complete-in-Box-Front.jpg',
		ebayLink: 'ebay.ca',
		checklistCart: true,
		checklistBox: true,
		checklistManual: true,
		checklistFoam: true,
		checklistSleeve: true,
		checklistPoster: null,
		checklistRegcard: true,
		checklistInsert: null,
		checklistSpecialOffer: true,
		price: '101'
	},
	{
		title: 'Darkwing Duck',
		boxArt: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Darkwing_Duck_NES_Cover.png/220px-Darkwing_Duck_NES_Cover.png',
		publisher: 'Capcom',
		releaseYear: '1992',
		platform: 'NES',
		imageLink: 'http://classicgamesblog.com/wp-content/uploads/2012/07/Contra-NES-Complete-in-Box-Front.jpg',
		ebayLink: 'https://www.ebay.ca/sch/i.html?_from=R40&_trksid=m570.l1313&_sacat=0&rt=nc&LH_PrefLoc=1&_trksid=p2045573.m1684&_nkw=darkwing+duck+nes+cib',
		checklistCart: false,
		checklistBox: true,
		checklistManual: true,
		checklistFoam: true,
		checklistSleeve: false,
		checklistPoster: null,
		checklistRegcard: null,
		checklistInsert: null,
		checklistSpecialOffer: true,
		price: '146'
	},
	{
		title: 'Duck Tales',
		boxArt: 'https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/1280x1280/products/24746/16242/Game%20Nintendo%20NES-701-2__14803.1394727176.jpg?c=2&imbypass=on',
		publisher: 'Capcom',
		releaseYear: '1989',
		platform: 'NES',
		imageLink: 'http://classicgamesblog.com/wp-content/uploads/2012/07/Contra-NES-Complete-in-Box-Front.jpg',
		ebayLink: 'https://www.ebay.ca/sch/i.html?_from=R40&_trksid=m570.l1313&_sacat=0&rt=nc&LH_PrefLoc=1&_trksid=p2045573.m1684&_nkw=duck+tales+nes+cib',
		checklistCart: true,
		checklistBox: true,
		checklistManual: true,
		checklistFoam: true,
		checklistSleeve: true,
		checklistPoster: null,
		checklistRegcard: null,
		checklistInsert: null,
		checklistSpecialOffer: true,
		price: '180'
	},
	{
		title: 'Super Mario Bros/Duck Hunt',
		boxArt: 'https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/1280x1280/products/24516/22894/SMB_DH_box__61365.1398107019.jpg?c=2&imbypass=on',
		publisher: 'Nintendo',
		releaseYear: '1988',
		platform: 'NES',
		imageLink: 'http://classicgamesblog.com/wp-content/uploads/2012/07/Contra-NES-Complete-in-Box-Front.jpg',
		ebayLink: 'https://www.ebay.ca/sch/i.html?_from=R40&_trksid=m570.l1313&_sacat=0&rt=nc&LH_PrefLoc=1&_trksid=p2045573.m1684&_nkw=super+mario+bros+nes+cib',
		checklistCart: true,
		checklistBox: true,
		checklistManual: true,
		checklistFoam: true,
		checklistSleeve: true,
		checklistPoster: null,
		checklistRegcard: null,
		checklistInsert: null,
		checklistSpecialOffer: true,
		price: '149'
	},
	{
		title: 'Super Mario Bros 2',
		boxArt: 'https://vignette.wikia.nocookie.net/mario/images/3/30/SMB2_box_art.png/revision/latest?cb=20120609143907',
		publisher: 'Nintendo',
		releaseYear: '1988',
		platform: 'NES',
		imageLink: 'http://classicgamesblog.com/wp-content/uploads/2012/07/Contra-NES-Complete-in-Box-Front.jpg',
		ebayLink: 'https://www.ebay.ca/sch/i.html?_from=R40&_trksid=m570.l1313&_sacat=0&rt=nc&LH_PrefLoc=1&_trksid=p2045573.m1684&_nkw=super+mario+bros+2+nes+cib',
		checklistCart: true,
		checklistBox: true,
		checklistManual: true,
		checklistFoam: true,
		checklistSleeve: true,
		checklistPoster: null,
		checklistRegcard: null,
		checklistInsert: null,
		checklistSpecialOffer: true,
		price: '45'
	},
	{
		title: 'Super Mario Bros 3',
		boxArt: 'https://cdn11.bigcommerce.com/s-ymgqt/images/stencil/1280x1280/products/24515/38665/SMB_3_box__32278.1515178584.jpg?c=2&imbypass=on',
		publisher: 'Nintendo',
		releaseYear: '1990',
		platform: 'NES',
		imageLink: 'http://classicgamesblog.com/wp-content/uploads/2012/07/Contra-NES-Complete-in-Box-Front.jpg',
		ebayLink: 'https://www.ebay.ca/sch/i.html?_from=R40&_trksid=m570.l1313&_sacat=0&rt=nc&LH_PrefLoc=1&_trksid=p2045573.m1684&_nkw=super+mario+bros+3+nes+cib',
		checklistCart: true,
		checklistBox: true,
		checklistManual: true,
		checklistFoam: true,
		checklistSleeve: true,
		checklistPoster: null,
		checklistRegcard: null,
		checklistInsert: null,
		checklistSpecialOffer: true,
		price: '52'
	}
];